interface BaseError {
  message: String!
}

type InvalidCredentialsError implements BaseError {
  message: String!
}

type UnauthorizedError implements BaseError {
  message: String!
}

type UnknownError implements BaseError {
  message: String!
}

type NotFoundError implements BaseError {
  message: String!
}
