# import User from 'user.typeDefs.gql'

type Query {
  users: [User]
}

type CreateUserInput {
  username: String!
  password: String!
  email: String!
  bio: String
  avatarUrl: String
}

type Mutation {
  createUser(
    password: String!
    username: String!
    email: String!
    bio: String
    avatarUrl: String
  ): User
}
