# import User from 'user.typeDefs.gql'
# import CreateUserResult from 'user.typeDefs.gql'
# import LoginResult from 'user.typeDefs.gql'
# import QueryUserResult from 'user.typeDefs.gql'
# import isUser from 'directives.typeDefs.gql'

type Query {
  findUser(id: String!): QueryUserResult
  findUsers: [User] @isUser
  findLoggedInUser: QueryUserResult @isUser
}

type Mutation {
  createUser(
    password: String!
    username: String!
    email: String!
    bio: String
    avatarUrl: String
  ): CreateUserResult!
  login(username: String!, password: String!): LoginResult!
}
