scalar Date

type User {
  id: ID!
  username: String!
  password: String!
  email: String!
  bio: String
  avatarUrl: String
  createdAt: Date!
}

type CreateUserInput {
  username: String!
  password: String!
  email: String!
  bio: String
  avatarUrl: String
}
