# import BaseError from 'error.typeDefs.gql'
# import UnknownError from 'error.typeDefs.gql'

scalar Date

type User {
  id: ID!
  username: String!
  password: String!
  email: String!
  bio: String
  avatarUrl: String
  createdAt: Date!
}

# TODO: validate user result
type UsernameExistsError implements BaseError {
  message: String!
}

type DuplicateEmailError implements BaseError {
  message: String!
}

union CreateUserResult = User | UnknownError

type LoginTokens {
  accessToken: String!
  refreshToken: String!
}

type InvalidCredentialsError implements BaseError {
  message: String!
}

union LoginResult = LoginTokens | UnknownError | InvalidCredentialsError
